[package]
name = "n2link-pymod"
version = "0.4.0-rc.1"
edition = "2024"

[lib]
name = "n2link_pymod"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.23", features = ["extension-module"] }
pyo3-async-runtimes = { version = "^0.23", features = ["tokio-runtime"] }
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
config.workspace = true
log4rs.workspace = true
log.workspace = true

n2link-core = { path = "../../crates/core", default-features = true, features = [
    "pymod", "default", "nodes_ai", "nodes_ai_text"
] }
# Node plug-ins:
n2link-nodes-dummy = { path = "../../node-plugins/n2link-nodes-dummy" }
